version: '2'
services:

  sweep-web:
    image: nginx
    container_name: sweep-web
    ports:
      - "8800:80"
      - "443:443"
    links:
      - sweep-php
      - sweep-mysql
    volumes:
      - ./docker/sites:/etc/nginx/conf.d
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - code

  sweep-php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: sweep-php
    working_dir: /var/www/default
    links:
      - sweep-mysql
    volumes_from:
      - code

  sweep-mysql:
    image: mysql:5.7
    container_name: sweep-mysql
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sweep
    ports:
      - 3307:3306

  code:
    image: busybox
    volumes:
      - ./api:/var/www/default

# COPY conf/my.cnf /etc/mysql/my.cnf
# - ./conf/php.ini:/etc/php/7.1/fpm/conf.d/40-custom.ini
# command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
